### ISSUE TITLE
But wait IT WORKS!

### ISSUE THREAD

**Issue by sshbio** [lopaka/instructions#6]
I bought this tiny laptop last year, I put Debian on it (without any modification it still boot).

But a single month after that, it stopped to boot (random crash and one day, it could not boot anymore), and putting the USB key with Debian could not make it boot at all.  I got OpenBSD booting on it, only once.

And today, thank to your guide, it can boot again!

So 40 minutes before, I had one old, noisy and unreliable laptop that I could not bring in class, and now, I also have this small laptop that I can use thank to you!

Thank you a lot!

**Comment by hipunk** [comment]
Hi,

I am extremely happy to read that I could help you out! And also thank you for telling me this!
In fact, I have written up another guide offline (about Linux Mint install), but it's not online yet because I was and still am currently quite busy and I needed 8.1 again, as this machine is the only one I'm using right now (I found that silent computing is best computing).

And well... I need built in sound on my computer, heh.

I also found some issues when booting debian. I tried 8.4.0 but it didn't work. 8.3.0 however, works flawless for me. Especially when you have a USB to Ethernet dongle (USB Wifi should also work, haven't tested it, but I could), because then it automagically installs 8.4.0 right away.
It doesn't even crash without any additional patches, but having to use USB devices to still be able to use the superb vanilla kernel (it has mine and RMS' birthday as version number, that's why it's so superb and awesome), is a tad annoying.

By the way: I installed from DVD, not via an USB flash memory stick.
I find these install medias more "voodoostable", but maybe that's just me.

Have a nice weekend!


Greetings,

HIPUNK

**Comment by sshbio** [comment]
I am answering a bit lately...

>I am extremely happy to read that I could help you out! And also thank
>you for telling me this!
>In fact, I have written up another guide offline (about Linux Mint
>install), but it's not online yet because I was and still am currently

No problem.

>quite busy and I needed 8.1 again, as this machine is the only one I'm
>using right now (I found that silent computing is best computing).

One reason why I bought it as well.

>And well... I need built in sound on my computer, heh.

Yes, it is so bad that OEM do not give the drivers.

>I also found some issues when booting debian. I tried 8.4.0 but it
>didn't work. 8.3.0 however, works flawless for me. Especially when you
>have a USB to Ethernet dongle (USB Wifi should also work, haven't
>tested it, but I could), because then it automagically installs 8.4.0
>right away.

I remember that I got it bootitg as well.  It may have been the 8.3, then.

>It doesn't even crash without any additional patches, but having to use
>USB devices to still be able to use the superb vanilla kernel (it has
>mine and RMS' birthday as version number, that's why it's so superb and
>awesome), is a tad annoying.

Oh, great ! :)

>By the way: I installed from DVD, not via an USB flash memory stick.
>I find these install medias more "voodoostable", but maybe that's just
>me.

These plastic circles never die.

>Have a nice weekend!

And he a nice week!

**Comment by sshbio** [comment]
I can confirm that it works with [lubuntu](http://lubuntu.net) 16.04.

You just saved me a couple of hundred Euros!

**Comment by RevealedFrom** [comment]
Happy for all you who were successful.

May I know how you guys get the wifi adapter working and connected to an AP during the installation process?

Thanks.

**Comment by hipunk** [comment]
I didn't but I recently sold it, so I cannot even test it anymore.

**Comment by RevealedFrom** [comment]
Lopaka, thank you for the amazing work you have here! I don't even understand the super-long multiline commands to build the USB disk, but it worked exactly as described!

I had a couple of hiccups during installation. The first time, the mouse pad didn't work, and I didn't know about Alt-F10 to activate the top menu to configure wifi.

The first $1 wifi adapter I used (which worked fine in Windows 10) didn't work. The second $4 wifi adapter (which looked exactly the same as the first one) worked fine.

On first time reboot after successful installation, the wifi adapter wasn't detected, but later it came back on.

I look forward to any updates that will allow the built-in wifi adapter to work.  And sound and mic too.

Cheers.

**Comment by lopaka** [comment]
Hello @RevealedFrom 

You are very welcome - glad someone benefits from the headaches I ran into.

The long command line for grub-mkimage includes all of the modules you need for grub.  The whole code block was meant to be copy/pasted into a file and run.  I think I'll add that as a script.

Interesting that the mouse pad didn't work - I haven't ran into that issue.  But good to know how to set the wifi if it doesn't work - I'll add that to the doc.

Investigating further for the built-in wifi adapter shows others are using an andoid driver.  It will take some more investigating, but luckily I got a hold of this laptop to test.  So, keep your eyes open.

Thanks!
